# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Andre's Site
tagline:             '100% Authentic Andre'
description:         'The only place on the web where you can find organic, fair-trade, non-GMO Andre'
url:                 https://prudhommea.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Andre Prudhomme
  url:               

# Custom vars
version:             1.0.0

# Pages Header
pages_list:
  About: '/about'
  Essays: '/essays'
  Photos: '/photos'
  Newsletter: '/newsletter'
  Archive: '/archive'
